# Generated by Django 3.2.20 on 2023-07-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_personmodel_custum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.AddField(
            model_name='personmodel',
            name='age',
            field=models.DateField(default=''),
        ),
    ]
