# Generated by Django 3.2.20 on 2023-07-24 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20230724_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='age',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
