# Generated by Django 3.2.20 on 2023-07-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_remove_personmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='age',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
