# Generated by Django 3.2.20 on 2023-07-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_personmodel_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmodel',
            name='illness_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='illness_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='illness_uz',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
