# Generated by Django 3.2.20 on 2023-07-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20230724_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='adress_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='adress_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='adress_uz',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='email_en',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='email_ru',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='email_uz',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='first_name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='first_name_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='first_name_uz',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='last_name_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='last_name_ru',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personmodel',
            name='last_name_uz',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
