# Generated by Django 3.2.20 on 2023-07-25 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20230725_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='doctor_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='doctor_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='doctor_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='patient_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='description_en',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='description_ru',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='description_uz',
            field=models.CharField(default='', max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='name_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='name_ru',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='name_uz',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='degree_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='degree_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='degree_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departmentmodel'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departmentmodel'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='department_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departmentmodel'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='specialization_en',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='specialization_ru',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='specialization_uz',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='diagnosis_en',
            field=models.CharField(default='', max_length=3030, null=True),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='diagnosis_ru',
            field=models.CharField(default='', max_length=3030, null=True),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='diagnosis_uz',
            field=models.CharField(default='', max_length=3030, null=True),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='patient_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='patient_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='patient_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='treatment_en',
            field=models.CharField(default='', max_length=2023, null=True),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='treatment_ru',
            field=models.CharField(default='', max_length=2023, null=True),
        ),
        migrations.AddField(
            model_name='medical_reccordmodel',
            name='treatment_uz',
            field=models.CharField(default='', max_length=2023, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='assigned_doctor_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='assigned_doctor_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='assigned_doctor_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='medical_history_en',
            field=models.CharField(default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='medical_history_ru',
            field=models.CharField(default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='patientmodel',
            name='medical_history_uz',
            field=models.CharField(default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='doctor_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='doctor_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='doctor_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctormodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='dosage_en',
            field=models.CharField(default='', max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='dosage_ru',
            field=models.CharField(default='', max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='dosage_uz',
            field=models.CharField(default='', max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='instructions_en',
            field=models.CharField(default='', max_length=1234, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='instructions_ru',
            field=models.CharField(default='', max_length=1234, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='instructions_uz',
            field=models.CharField(default='', max_length=1234, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='medication_en',
            field=models.CharField(default='', max_length=299, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='medication_ru',
            field=models.CharField(default='', max_length=299, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='medication_uz',
            field=models.CharField(default='', max_length=299, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='patient_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='patient_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='prescriptionmodel',
            name='patient_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.patientmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='department_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departmentmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='department_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departmentmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='department_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departmentmodel'),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='job_en',
            field=models.CharField(default='', max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='job_ru',
            field=models.CharField(default='', max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='job_uz',
            field=models.CharField(default='', max_length=99, null=True),
        ),
    ]
